// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU-TsK4G62ZAlohYhyiZ8RSp5E-p10w0M',
    appId: '1:461639416996:web:7107c00d7eced5ea6d7a31',
    messagingSenderId: '461639416996',
    projectId: 'habits-of-a-happy-brain',
    authDomain: 'habits-of-a-happy-brain.firebaseapp.com',
    storageBucket: 'habits-of-a-happy-brain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7sqSSgKslUFIdBdTdvM6103_-L8RLjY',
    appId: '1:461639416996:android:0af3afda88af502e6d7a31',
    messagingSenderId: '461639416996',
    projectId: 'habits-of-a-happy-brain',
    storageBucket: 'habits-of-a-happy-brain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArI83jHO8FaiHBiDmGxq4zLC98SOHQyJ8',
    appId: '1:461639416996:ios:532f5cf7121ba4f26d7a31',
    messagingSenderId: '461639416996',
    projectId: 'habits-of-a-happy-brain',
    storageBucket: 'habits-of-a-happy-brain.appspot.com',
    iosClientId: '461639416996-ieb5iobiknsrucu5jv7bln0g4lkcnetf.apps.googleusercontent.com',
    iosBundleId: 'com.example.habits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArI83jHO8FaiHBiDmGxq4zLC98SOHQyJ8',
    appId: '1:461639416996:ios:532f5cf7121ba4f26d7a31',
    messagingSenderId: '461639416996',
    projectId: 'habits-of-a-happy-brain',
    storageBucket: 'habits-of-a-happy-brain.appspot.com',
    iosClientId: '461639416996-ieb5iobiknsrucu5jv7bln0g4lkcnetf.apps.googleusercontent.com',
    iosBundleId: 'com.example.habits',
  );
}
